async function errorInside() {
    console.log('error inside function')
}

module.exports = errorInside